// Complete synthetic story: UI -> real HTTP -> private store -> agent lease -> UI.
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {chromium} from 'playwright';
import {pythonExecutable} from '../runtime-config.mjs';
const fixture=spawn(pythonExecutable(),['-E','-s','-S',fileURLToPath(new URL('./contacts_browser_fixture.py',import.meta.url))],{cwd:fileURLToPath(new URL('.',import.meta.url)),windowsHide:true,stdio:['ignore','pipe','pipe']});
let browser,stderr='';fixture.stderr.on('data',c=>stderr+=c.toString());
try{
 const ready=await new Promise((resolve,reject)=>{let output='';const timer=setTimeout(()=>reject(Error('Fixture timeout: '+stderr)),20000);fixture.stdout.on('data',c=>{output+=c;if(output.includes('\n')){clearTimeout(timer);try{resolve(JSON.parse(output.split('\n')[0]));}catch(e){reject(e);}}});fixture.on('error',reject);fixture.on('exit',code=>{clearTimeout(timer);reject(Error('Fixture exit '+code+': '+stderr));});});
 assert.equal(ready.synthetic,true);const origin=`http://127.0.0.1:${ready.port}`;
 browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1100}});page.setDefaultTimeout(15000);
 const errors=[],external=[],operations=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('400 (Bad Request)'))errors.push(m.text());});
 await page.route('**/*',route=>{if(!route.request().url().startsWith(origin+'/')){external.push(route.request().url());return route.abort();}return route.continue();});
 page.on('request',r=>{if(r.url().endsWith('/api/operation'))operations.push(r.postDataJSON().tool);});
 await page.goto(origin);await page.getByText('Private records workspace ready.',{exact:false}).waitFor();
 assert.equal(await page.locator('#map .state').count(),51);
 await page.locator('#contact-panel>summary').click();await page.locator('#contact-summary').getByText('county/role pairs',{exact:false}).waitFor();
 await page.locator('#contact-state').selectOption('MI');await page.waitForFunction(()=>document.querySelector('#contact-summary')?.textContent.startsWith('83 county/role pairs'));
 assert.match(await page.locator('#contact-summary').innerText(),/1 current verified/);
 const alcona=()=>page.locator('[data-contact-id="county:26001:public_records"]');const alger=()=>page.locator('[data-contact-id="county:26003:public_records"]');
 assert.match(await alcona().innerText(),/Verified email · current/);assert.match(await alger().innerText(),/Needs recheck/);
 assert.match(await page.locator('#contact-source').innerText(),/Census Bureau, 2025/);
 assert.deepEqual(errors,[]);
 const screenshot=path.join(tmpdir(),'civicrelay-contacts-synthetic.png');await page.locator('#contact-panel').screenshot({path:screenshot});
 const api=async(tool,args={})=>{const response=await page.request.post(origin+'/api/operation',{headers:{Origin:origin,'X-Records-Desk':'1'},data:{tool,arguments:args}});const r=await response.json();if(!r.ok)throw Error(r.error);return r.result;};
 const clickOperation=async(name,action)=>{const pending=page.waitForResponse(r=>r.url().endsWith('/api/operation')&&r.request().postDataJSON()?.tool===name);await action();const r=await (await pending).json();assert.equal(r.ok,true,r.error);return r.result;};
 await page.locator('#contact-all').uncheck();await page.locator('#contact-counties').selectOption(['county:26001','county:26003','county:26005']);
 const created=await clickOperation('desk_create_contact_batch',()=>page.getByRole('button',{name:'Queue missing / stale contacts',exact:true}).click());
 assert.equal(created.batch.task_count,2);assert.equal(created.batch.skipped.current,1);assert.equal(created.agent_started,false);
 await page.locator('#contact-agent-prompt').waitFor();assert.match(await page.locator('#contact-agent-prompt').inputValue(),/desk_claim_contact_tasks/);
 const batch=created.batch,first=(await api('desk_claim_contact_tasks',{batch_id:batch.id,worker_id:'synthetic-worker-a',limit:1})).tasks[0];
 const second=(await api('desk_claim_contact_tasks',{batch_id:batch.id,worker_id:'synthetic-worker-b',limit:1})).tasks[0];assert.notEqual(first.id,second.id);
 const day=new Date().toISOString().slice(0,10),result={outcome:'verified',checked_on:day,note:'Synthetic <img src=x onerror=alert(1)> is text, never executable.',contacts:[{department:'Synthetic FOIA office',email:'updated@example.test',route_type:'designated_custodian',source_url:'https://example.gov/records'}],sources:[{url:'https://example.gov/records',title:'Synthetic official records page',publisher:'Synthetic County',checked_on:day,official:true,evidence:'Synthetic published email and custodian role.'}]};
 await api('desk_complete_contact_task',{batch_id:batch.id,task_id:first.id,lease_token:first.lease_token,result});
 await api('desk_complete_contact_task',{batch_id:batch.id,task_id:second.id,lease_token:second.lease_token,result:{...result,outcome:'no_email_found',contacts:[],note:'Synthetic portal-only search result. No email guessed.'}});
 await clickOperation('desk_find_contacts',()=>page.getByRole('button',{name:'Look up saved contacts',exact:true}).click());
 await page.waitForFunction(()=>document.querySelector('[data-contact-id="county:26003:public_records"]')?.textContent.includes('updated@example.test'));
 await clickOperation('desk_list_contact_batches',()=>page.getByRole('button',{name:'Refresh batch progress',exact:true}).click());
 assert.match(await page.locator('#contact-batches').innerText(),/complete/);assert.match(await page.locator('#contact-batches').innerText(),/1 researched but unresolved/);
 await alger().getByRole('button').click();await page.getByRole('button',{name:'Add / update research',exact:true}).click();
 await page.locator('#contact-note').fill('Unsaved synthetic evidence');await alcona().getByRole('button').click();assert.match(await page.locator('#notice').innerText(),/Save or discard contact evidence/);assert.equal(await page.locator('#contact-note').inputValue(),'Unsaved synthetic evidence');
 await page.getByRole('button',{name:'Discard contact edits',exact:true}).click();await page.getByRole('button',{name:'Add / update research',exact:true}).click();await page.locator('#contact-note').fill('Synthetic operator recheck.');
 await clickOperation('desk_save_contact',()=>page.getByRole('button',{name:'Save contact evidence',exact:true}).click());await page.getByText('Contact evidence saved privately.',{exact:false}).waitFor();
 const saved=await api('desk_get_contact',{county_id:'county:26003',role:'public_records'});assert.equal(saved.contact.revision,3);assert.equal(saved.history.length,3);
 await page.reload();await page.getByText('Private records workspace ready.',{exact:false}).waitFor();await page.locator('#contact-panel>summary').click();await page.locator('#contact-summary').getByText('county/role pairs',{exact:false}).waitFor();await page.locator('#contact-state').selectOption('MI');await page.waitForFunction(()=>document.querySelector('#contact-summary')?.textContent.startsWith('83 county/role pairs'));
 assert.match(await alger().innerText(),/updated@example.test/);assert.match(await page.locator('[data-contact-id="county:26005:public_records"]').innerText(),/No email found/);
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);assert.equal(operations.filter(x=>/sync_mail|send_email|publish|capture|export/.test(x)).length,0);
 console.log(JSON.stringify({ok:true,synthetic:true,stories:['all-county-inventory-and-freshness','gap-batch-no-duplicate-workers','agent-result-to-directory','unresolved-remains-visible','safe-text-evidence','dirty-edit-preservation','history-and-reload','mobile-width'],screenshot,external_actions:0}));
}finally{await browser?.close();fixture.kill();}
